project:
  type: manuscript
  output-dir: _output
  render:
    - index.qmd

format:
  pdf:
    documentclass: article
    geometry: margin=1in
    fontsize: 11pt
    linestretch: 1.5
    keep-tex: false
    number-sections: true
    colorlinks: true
  ipynb:
    execute:
      echo: true
      warning: false

bibliography: library.bib
csl: https://www.zotero.org/styles/plos-computational-biology

execute:
  echo: true
  warning: false
  cache: true
  freeze: auto

julia:
  exeflags: ["--threads=4", "-O3"]
