name = "JuliaForIDM"
authors = ["Samuel Abbott <contact@samabbott.co.uk>"]
version = "0.1.1"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[compat]
Distributions = "0.25"
DocStringExtensions = "0.9"
Turing = "0.38"
julia = "1.11"
