version: '3'

tasks:
  default:
    desc: "Render the paper (main development task)"
    deps: [instantiate]
    cmds:
      - quarto render

  install:
    desc: "Install Julia 1.11.7 using juliaup"
    cmds:
      - juliaup add 1.11.7
    status:
      - juliaup status | grep -q "1.11.7"

  instantiate:
    desc: "Activate and instantiate the Julia project environment"
    deps: [install]
    cmds:
      - julia +1.11.7 -e "using Pkg; Pkg.activate(\".\"); Pkg.instantiate()"
    sources:
      - Project.toml
      - Manifest.toml
    generates:
      - LocalPreferences.toml

  repl:
    desc: "Launch Julia REPL with project environment active"
    deps: [instantiate]
    cmds:
      - julia +1.11.7 -i -e "using Pkg; Pkg.activate(\".\")"
    interactive: true

  preview:
    desc: "Preview the paper with live reload"
    deps: [instantiate]
    cmds:
      - quarto preview
    interactive: true

  test:
    desc: "Run Julia tests"
    deps: [instantiate]
    cmds:
      - julia +1.11.7 -e "using Pkg; Pkg.activate(\".\"); Pkg.test()"