project:
  type: manuscript
  output-dir: _output

format:
  pdf:
    documentclass: article
    template-partials:
      - title.tex
    toc: true
    number-sections: true
    colorlinks: true
    geometry:
      - margin=1in

bibliography:
  - references.bib
  - library.bib
csl: nature.csl

execute:
  echo: true
  warning: false

jupyter: julia-1.9
