name: Build Paper

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-paper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.4.549

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.9'

      - name: Install Julia dependencies
        run: |
          julia --project=. -e '
            using Pkg
            Pkg.instantiate()'

      - name: Render Paper
        run: |
          cd paper
          quarto render paper.qmd

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: paper/_output/paper.pdf

      - name: Upload HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper-html
          path: paper/_output/paper.html
